---

###
### Enable sudo (required for docker service)
###
sudo: required


###
### Language
###
language: minimal


###
### Add services
###
services:
  - docker


###
### Build Matrix
###
env:
  matrix:
    - VERSION=5.6
    - VERSION=7.0
    - VERSION=7.1
    - VERSION=7.2
    - VERSION=7.3
    - VERSION=latest


###
### Install requirements
###
install:
  - retry() {
      for ((n=0; n<10; n++)); do
        echo "[${n}] ${*}";
        if eval "${*}"; then
          return 0;
        fi;
      done;
      return 1;
    }


###
### Check generation changes, build and test
###
before_script:
  - retry make lint
  - if [ "${VERSION}" != "latest" ]; then retry make build TAG=${VERSION}-cli-alpine; else retry make build; fi
  - if [ "${VERSION}" != "latest" ]; then retry make test  TAG=${VERSION}-cli-alpine; else retry make test;  fi


###
### Push to Dockerhub
###
script:
  # Push to docker hub on success
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      while ! make login USER="${DOCKER_USERNAME}" PASS="${DOCKER_PASSWORD}"; do sleep 1; done;
      if [ -n "${TRAVIS_TAG}" ]; then
        while ! make push TAG="${VERSION}-${TRAVIS_TAG}"; do sleep 1; done;
      elif [ "${TRAVIS_BRANCH}" == "master" ]; then
        while ! make push TAG=${VERSION}; do sleep 1; done;
      elif [[ ${TRAVIS_BRANCH} =~ ^(release-[.0-9]+)$ ]]; then
        while ! make push TAG="${VERSION}-${TRAVIS_BRANCH}"; do sleep 1; done;
      else
        echo "Skipping branch ${TRAVIS_BRANCH}";
      fi
    else
      echo "Skipping push on PR";
    fi
